# Generated by Django 5.2.8 on 2025-11-13 09:08

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ForeignKey(blank=True, default=main.models.get_default_role, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.role'),
        ),
    ]
