# Generated by Django 5.2.8 on 2025-11-13 14:03

import django.contrib.postgres.fields
import django.db.models.deletion
import main.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDiscussions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'course_discussions',
            },
        ),
        migrations.CreateModel(
            name='CourseModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'course_modules',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default_course.png', null=True, upload_to=main.models.course_image_upload_to)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('expertise_level', models.CharField(blank=True, max_length=100, null=True)),
                ('prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('objectives', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('isPaid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='ModuleQuizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'module_quizes',
            },
        ),
        migrations.CreateModel(
            name='ModuleTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300), blank=True, default=list, null=True, size=None)),
                ('files_description', models.TextField(blank=True, null=True)),
                ('videos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300), blank=True, default=list, null=True, size=None)),
                ('videos_description', models.TextField(blank=True, null=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300), blank=True, default=list, null=True, size=None)),
                ('images_description', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Enter duration as HH:MM:SS', null=True)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'module_topics',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('tf', 'True/False'), ('text', 'Text Response')], default='mcq', max_length=50)),
                ('question_text', models.TextField()),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('correct_answer', models.CharField(max_length=255)),
                ('marks', models.IntegerField(default=1)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'quiz_questions',
            },
        ),
        migrations.CreateModel(
            name='QuizResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('selected_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'quiz_question_response',
            },
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('topics_completed', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('quiz_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_module_progress',
            },
        ),
        migrations.CreateModel(
            name='UsersCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'users_course_enrollment',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['action'], name='permission_action_d0629e_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['created_at'], name='permission_created_b451db_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='role_name_796487_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['created_at'], name='role_created_92df09_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['guid'], name='users_guid_78b69b_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['role'], name='users_role_id_7a277c_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddField(
            model_name='coursediscussions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursemodules',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses'),
        ),
        migrations.AddField(
            model_name='coursediscussions',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses'),
        ),
        migrations.AddField(
            model_name='modulequizes',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursemodules'),
        ),
        migrations.AddField(
            model_name='moduletopics',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursemodules'),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modulequizes'),
        ),
        migrations.AddField(
            model_name='quizresponses',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.quizquestions'),
        ),
        migrations.AddField(
            model_name='quizresponses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coursemodules'),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userscourseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courses'),
        ),
        migrations.AddField(
            model_name='userscourseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['title'], name='courses_title_0466cc_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['status'], name='courses_status_67f368_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['instructor'], name='courses_instruc_77fba4_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['isPaid'], name='courses_isPaid_b1b72d_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['isFeatured'], name='courses_isFeatu_742037_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['expertise_level'], name='courses_experti_a9c0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['created_at'], name='courses_created_0aa93c_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodules',
            index=models.Index(fields=['course', 'order'], name='course_modu_course__2c6358_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodules',
            index=models.Index(fields=['name'], name='course_modu_name_1b1919_idx'),
        ),
        migrations.AddIndex(
            model_name='moduletopics',
            index=models.Index(fields=['module', 'order'], name='module_topi_module__30139f_idx'),
        ),
        migrations.AddIndex(
            model_name='moduletopics',
            index=models.Index(fields=['name'], name='module_topi_name_a8c8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresponses',
            index=models.Index(fields=['user', 'question'], name='quiz_questi_user_id_df545e_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresponses',
            index=models.Index(fields=['is_correct'], name='quiz_questi_is_corr_c753cb_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresponses',
            index=models.Index(fields=['answered_at'], name='quiz_questi_answere_bd80dc_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['user', 'module'], name='user_module_user_id_dd6db3_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['quiz_completed'], name='user_module_quiz_co_97681f_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['completed_at'], name='user_module_complet_6a07bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermoduleprogress',
            unique_together={('user', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='userscourseenrollment',
            unique_together={('user', 'course')},
        ),
    ]
