# Generated by Django 5.2.8 on 2025-11-16 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_coursediscussions_coursemodules_courses_modulequizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmissionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('feedback', models.TextField(help_text='Instructor feedback on quiz submission')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall score for the quiz submission', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=200, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_feedbacks_given', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_feedbacks', to='main.modulequizes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_feedbacks_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_submission_feedback',
                'indexes': [models.Index(fields=['user', 'quiz'], name='quiz_submis_user_id_d40ee4_idx'), models.Index(fields=['instructor'], name='quiz_submis_instruc_3d24f6_idx'), models.Index(fields=['created_at'], name='quiz_submis_created_d57ba2_idx')],
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
