# Generated by Django 5.2.8 on 2026-01-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quizsubmissionfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
