# Generated by Django 5.2.8 on 2026-01-27 05:50

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_courses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, default='course_image/default_course.png', null=True, upload_to=main.models.course_image_upload_to),
        ),
    ]
