# Generated by Django 5.2.8 on 2026-02-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
