# Generated by Django 5.2.8 on 2026-03-09 08:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_users_age_users_gender'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moduletopics',
            name='module_topi_module__30139f_idx',
        ),
        migrations.RemoveField(
            model_name='moduletopics',
            name='order',
        ),
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
        migrations.AddField(
            model_name='courses',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='modulequizes',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='main.courses'),
        ),
        migrations.AddField(
            model_name='moduletopics',
            name='audio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='moduletopics',
            name='audio_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduletopics',
            name='resource_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='moduletopics',
            name='topic_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='modulequizes',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='main.coursemodules'),
        ),
        migrations.AddIndex(
            model_name='moduletopics',
            index=models.Index(fields=['module', 'topic_order'], name='module_topi_module__d90506_idx'),
        ),
    ]
