# Generated by Django 5.2.8 on 2026-03-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_organizations_courses_learning_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='venue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
