"""
Django settings for KFCAcademy project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import django
import os
import django.db.models.signals
import sentry_sdk

from pathlib import Path
from django.utils.encoding import force_str
from datetime import timedelta
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

django.utils.encoding.force_text = force_str


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY','django-insecure-m-i6_)z5_-aayvla&p$!b^5!lv$c+14n^1!fzr5*k1h5gvxv=h')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ["true", "1", "yes"]

if DEBUG == True:
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        '8a6132f56240.ngrok-free.app',
        '*',  # Allow all hosts in development for easier testing
    ]
else:
    ALLOWED_HOSTS = [
        'api.fpckenya.co.ke',
        'fpckenya.co.ke',
        '8a6132f56240.ngrok-free.app',
        'academy.fpckenya.co.ke',
        '65.109.11.105'
    ]


# Application definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

APPLICATION_APPS = [
    'drf_yasg',
    'rest_framework',
    'corsheaders',
    'django_rest_passwordreset',
    'main'
]


INSTALLED_APPS = DJANGO_APPS + APPLICATION_APPS


MIDDLEWARE = [
    'KFCAcademy.middleware.HandleDisallowedHostMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'main.middleware.CurrentUserLoggingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

# CORS Configuration for Frontend Access
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:5175',    # Frontend port
    'http://localhost:5173',    # Vite default port
    'http://127.0.0.1:3000',
    'http://127.0.0.1:5175',    # Frontend port
    'http://127.0.0.1:5173',    # Vite default port
    'http://fpckenya.co.ke',
    'http://academy.fpckenya.co.ke'
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://.*\.fpckenya\.co.ke$',
    r'^https://.*\.vercel\.app$',
    r'^http://localhost:[3-9]\d{3}$',      # Allow localhost with ports 3000-9999
    r'^http://127\.0\.0\.1:[3-9]\d{3}$',   # Allow 127.0.0.1 with ports 3000-9999
    r'^https://.*\.ngrok\.io$',             # Allow ngrok domains
    r'^https://.*\.ngrok-free\.app$',       # Allow ngrok-free domains
]

# Allow credentials (needed for JWT tokens and cookies)
CORS_ALLOW_CREDENTIALS = True

# Expose headers that frontend might need
CORS_EXPOSE_HEADERS = [
    'content-type',
    'authorization',
    'x-total-count',
    'x-pagination-count',
]

# Allow common headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin',
    'access-control-allow-headers',
    'access-control-allow-methods',
]

# Allow common HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# For development, allow all origins (comment out for production)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'KFCAcademy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries' : {
                'staticfiles': 'django.templatetags.static', 
            }
        },
    },
]

WSGI_APPLICATION = 'KFCAcademy.wsgi.application'


SWAGGER_SETTINGS = {
   'USE_SESSION_AUTH': False
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_MODEL_SERIALIZER_CLASS': (
        'rest_framework.serializers.ModelSerializer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'DEFAULT_SCHEMA_CLASS':'rest_framework.schemas.coreapi.AutoSchema'
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=2),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('JWT',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'kfc_development'),
            'USER': os.environ.get('POSTGRES_USER', 'devuser'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'devuser'),
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),  # Use default if not set
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'fpc_prod'),
            'USER': os.environ.get('POSTGRES_USER', 'fpcmain'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', '6lmX44pBd2J2'),
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),  # Use default if not set
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles/")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')

# MEDIA_ROOT = '/var/www/compliance_tool_media'
MEDIA_URL = '/media/'


AUTH_USER_MODEL = 'main.Users'

USERNAME_FIELD = 'email'


DJANGO_REST_MULTITOKENAUTH_RESET_TOKEN_EXPIRY_TIME = 1
DJANGO_REST_PASSWORDRESET_NO_INFORMATION_LEAKAG = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


EMAIL_HOST = "mail.fpckenya.co.ke"
EMAIL_PORT = 587
EMAIL_HOST_USER = "noreply@fpckenya.co.ke"
EMAIL_HOST_PASSWORD = "$AWlI;9xW+{[#YZX"
EMAIL_USE_SSL = False
EMAIL_USE_TLS = True  # ⚠️ must be False with 465
DEFAULT_FROM_EMAIL = '"KFC Academy" <kfc@kfc.co.ke>'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '[%(asctime)s][%(levelname)s] %(process)d %(thread)d '
                      '%(name)s %(filename)s:%(funcName)s:%(lineno)d | %(message)s',
        },
    },
    'handlers': {
        'sentry': {
            'level': 'WARNING',
            'class': 'sentry_sdk.integrations.logging.EventHandler',
            'formatter': 'default'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'default'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'django_debug.log',  # Your log file path
        },
    },
    'root': {
        'level': 'INFO',
        'handlers': ['file','sentry','console']
    },
    'loggers': {
        'django.request': {
            'handlers': ['file','sentry', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django': {
            'handlers': ['file','sentry','console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

sentry_logging = LoggingIntegration(
    level="ERROR",  # Capture warnings and errors
    event_level="ERROR",  # Only send errors to Sentry
)

sentry_sdk.init(
    dsn="https://e217cc3dedf3727c6be44ef6d3ebb86f@o1064579.ingest.us.sentry.io/4510356317011969",
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for tracing.
    traces_sample_rate=1.0,
    _experiments={
        # Set continuous_profiling_auto_start to True
        # to automatically start the profiler on when
        # possible.
        "continuous_profiling_auto_start": True,
    },
    integrations=[
        DjangoIntegration(
            transaction_style='url',
            middleware_spans=True,
            signals_spans=True,
            signals_denylist=[
                django.db.models.signals.pre_init,
                django.db.models.signals.post_init,
            ],
            cache_spans=False,
            http_methods_to_capture=("CONNECT", "DELETE", "GET", "PATCH", "POST", "PUT", "TRACE",),
        ),
        sentry_logging
    ],
    send_default_pii=True
)